import time
from selenium import webdriver
driver = webdriver.Chrome("/Users/wzz/Desktop/chromedriver")
driver.get("file:///Users/wzz/Desktop/Research/scriptRepair/WebRL/website/amazon/old/index.html")
el = driver.find_element_by_id("nav-cart")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/header[1]/div[1]/div[1]/div[3]/div[1]/form[1]/div[2]/div[1]/input[1]")
el = driver.find_element_by_id("nav-orders")
el = driver.find_element_by_link_text("Today's Deals")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/header[1]/div[1]/div[1]/div[1]/div[1]/a[1]/span[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/header[1]/div[1]/div[2]/div[2]/div[1]/a[1]/span[1]")
el = driver.find_element_by_id("nav-link-prime")
el = driver.find_element_by_id("twotabsearchtextbox")
el = driver.find_element_by_id("nav-link-accountList")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/header[1]/div[1]/div[2]/div[3]/div[1]/div[1]/a[4]")
el = driver.find_element_by_link_text("Amazon")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/header[1]/div[1]/div[2]/div[2]/div[1]/a[5]/span[3]")
