import time
from selenium import webdriver
driver = webdriver.Chrome("/Users/wzz/Desktop/chromedriver")
driver.get("file:///Users/wzz/Desktop/Research/scriptRepair/WebRL/website/chase/old/index.html")
el = driver.find_element_by_link_text("checking account")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/footer[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/h2[1]")
el = driver.find_element_by_link_text("mortgage rates")
el = driver.find_element_by_link_text("before you apply")
el = driver.find_element_by_link_text("Instagram")
el = driver.find_element_by_link_text("free credit score")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/footer[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[4]/div[1]/h2[1]")
el = driver.find_element_by_link_text("applying for a mortgage")
el = driver.find_element_by_link_text("car loan")
el = driver.find_element_by_link_text("LinkedIn")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/footer[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[8]/div[1]/h2[1]")
el = driver.find_element_by_link_text("credit cards")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/footer[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[7]/div[1]/h2[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/footer[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/h2[1]")
el = driver.find_element_by_link_text("refinance")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/footer[1]/div[1]/div[1]/div[1]/div[1]/div[2]/span[1]")
el = driver.find_element_by_link_text("Twitter")
el = driver.find_element_by_link_text("credit card")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/footer[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[5]/div[1]/h2[1]")
el = driver.find_element_by_link_text("Pinterest")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/footer[1]/div[1]/div[2]/div[1]/div[1]/div[1]/p[1]")
el = driver.find_element_by_link_text("mortgage calculator")
el = driver.find_element_by_link_text("HELOC calculator")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/footer[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[6]/div[1]/h2[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/footer[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/h2[1]")
el = driver.find_element_by_link_text("mortgage")
el = driver.find_element_by_link_text("Facebook")
el = driver.find_element_by_link_text("Home Equity Line of Credit")
el = driver.find_element_by_link_text("financial advisor")
el = driver.find_element_by_link_text("YouTube")
el = driver.find_element_by_link_text("cash back")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[7]/main[1]/div[1]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[9]/div[1]/div[1]/a[1]/div[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[7]/main[1]/div[1]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[10]/div[1]/div[1]/a[1]/div[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/footer[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[9]/div[1]/div[1]")
