import time
from selenium import webdriver
driver = webdriver.Chrome("/Users/wzz/Desktop/chromedriver")
driver.get("file:///Users/wzz/Desktop/Research/scriptRepair/WebRL/website/dropbox/old/index.html")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[12]/div[1]/main[1]/section[3]/section[1]/div[1]/div[2]/div[2]/span[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[12]/div[1]/div[1]/nav[1]/div[1]/button[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[12]/div[1]/main[1]/section[3]/section[1]/div[1]/div[1]/h2[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[12]/div[1]/main[1]/section[3]/section[2]/div[1]/div[1]/section[1]/article[1]/div[1]/div[1]/h2[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[12]/div[1]/div[1]/nav[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[12]/div[1]/main[1]/section[1]/div[1]/div[2]/div[1]/div[1]/div[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[12]/div[1]/main[1]/section[3]/section[2]/div[1]/div[3]/section[1]/article[1]/div[1]/div[1]/h2[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[12]/div[1]/main[1]/section[3]/section[1]/div[1]/div[2]/div[1]/span[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[12]/div[1]/div[1]/nav[1]/div[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[12]/div[1]/main[1]/section[1]/div[1]/div[2]/div[1]/div[2]/span[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[12]/div[1]/main[1]/section[3]/section[2]/div[1]/div[2]/section[1]/article[1]/div[1]/div[1]/h2[1]")
