import time
from selenium import webdriver
driver = webdriver.Chrome("/Users/wzz/Desktop/chromedriver")
driver.get("https://web.archive.org/web/20180601235610if_/https://www.ebay.com/")
el = driver.find_element_by_id("gh-cart")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/div[1]/ul[1]/li[11]/a[1]")
el = driver.find_element_by_link_text("Saved")
el = driver.find_element_by_link_text("Home & Garden")
el = driver.find_element_by_link_text("Daily Deals")
el = driver.find_element_by_id("gh-btn")
el = driver.find_element_by_link_text("Fashion")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/div[1]/ul[1]/li[9]/a[1]")
el = driver.find_element_by_id("gh-eb-My")
el = driver.find_element_by_id("gh-l-h1")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/div[1]/ul[1]/li[12]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/div[1]/ul[1]/li[1]")
el = driver.find_element_by_link_text("Sign in")
el = driver.find_element_by_link_text("Help & Contact")
el = driver.find_element_by_id("gh-ac")
el = driver.find_element_by_id("gh-eb-Alerts")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/div[1]/ul[1]/li[10]/a[1]")
el = driver.find_element_by_link_text("Motors")
el = driver.find_element_by_link_text("Collectibles & Art")
el = driver.find_element_by_id("gh-as-td")
el = driver.find_element_by_link_text("register")
el = driver.find_element_by_link_text("Electronics")
el = driver.find_element_by_link_text("Sporting Goods")
el = driver.find_element_by_link_text("Sell")
el = driver.find_element_by_id("gh-shop-a")
