import time
from selenium import webdriver
driver = webdriver.Chrome("/Users/wzz/Desktop/chromedriver")
driver.get("file:///Users/wzz/Desktop/Research/scriptRepair/WebRL/website/ebay/old/index.html")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/div[1]/ul[2]/li[4]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/div[1]/ul[1]/li[11]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/div[1]/ul[1]/li[2]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/div[1]/ul[1]/li[7]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/div[1]/ul[1]/li[2]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/table[1]/tbody[1]/tr[1]/td[3]/form[1]/table[1]/tbody[1]/tr[1]/td[3]/input[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/div[1]/ul[1]/li[4]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/div[1]/ul[1]/li[9]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/div[1]/ul[2]/li[2]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/table[1]/tbody[1]/tr[1]/td[1]/h1[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/div[1]/ul[1]/li[12]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/div[1]/ul[1]/li[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/div[1]/ul[1]/li[1]/span[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/div[1]/ul[1]/li[4]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/table[1]/tbody[1]/tr[1]/td[3]/form[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/div[1]/input[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/div[1]/ul[2]/li[3]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/div[1]/ul[1]/li[10]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/div[1]/ul[1]/li[3]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/div[1]/ul[1]/li[6]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/table[1]/tbody[1]/tr[1]/td[3]/form[1]/table[1]/tbody[1]/tr[1]/td[4]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/div[1]/ul[1]/li[1]/span[1]/span[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/div[1]/ul[1]/li[5]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/div[1]/ul[1]/li[8]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/div[1]/ul[2]/li[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/table[1]/tbody[1]/tr[1]/td[2]/div[1]/button[1]")
