import time
from selenium import webdriver
driver = webdriver.Chrome("/Users/wzz/Desktop/chromedriver")
driver.get("file:///Users/wzz/Desktop/Research/scriptRepair/WebRL/website/espn/old/index.html")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[3]/div[1]/footer[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[5]/div[1]/ul[1]/li[6]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[7]/div[1]/ul[1]/li[2]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[1]/div[1]/ul[1]/header[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[5]/div[1]/ul[1]/li[3]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[6]/div[1]/ul[1]/li[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[7]/div[1]/ul[1]/li[4]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[2]/div[1]/header[1]/h2[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[5]/div[1]/header[1]/h2[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[5]/div[1]/ul[1]/li[5]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/div[2]/header[1]/div[2]/h1[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[1]/div[1]/header[1]/h2[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[5]/div[1]/ul[1]/li[2]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[3]/div[1]/header[1]/h2[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[7]/div[1]/header[1]/h2[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[6]/div[1]/header[1]/h2[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[7]/div[1]/ul[1]/li[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[5]/div[1]/ul[1]/li[4]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/div[2]/section[1]/div[1]/div[1]/div[1]/div[2]/button[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[6]/div[1]/ul[1]/li[2]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[7]/div[1]/ul[1]/li[3]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[3]/div[1]/header[1]/h1[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[5]/div[1]/ul[1]/li[1]/a[1]")
