import time
from selenium import webdriver
driver = webdriver.Chrome("/Users/wzz/Desktop/chromedriver")
driver.get("file:///Users/wzz/Desktop/Research/scriptRepair/WebRL/website/espn/old/index.html")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[3]/div[1]/footer[1]/a[1]")
el = driver.find_element_by_name("&lpos=fp:sites:6:secnetwork")
el = driver.find_element_by_name("&lpos=fp:followespn:2:twitter")
el = driver.find_element_by_name("&lpos=espnplus:leftrail:upsellmodule")
el = driver.find_element_by_name("&lpos=fp:sites:3:espnw")
el = driver.find_element_by_name("&lpos=fp:apps:1:espn")
el = driver.find_element_by_name("&lpos=fp:followespn:4:snapchat")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[2]/div[1]/header[1]/h2[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[5]/div[1]/header[1]/h2[1]")
el = driver.find_element_by_name("&lpos=fp:sites:5:xgames")
el = driver.find_element_by_name("&lpos=sitenavdefault&lid=sitenav_main-logo")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[1]/div[1]/header[1]/h2[1]")
el = driver.find_element_by_name("&lpos=fp:sites:2:theundefeated")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[3]/div[1]/header[1]/h2[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[7]/div[1]/header[1]/h2[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[1]/article[6]/div[1]/header[1]/h2[1]")
el = driver.find_element_by_name("&lpos=fp:followespn:1:facebook")
el = driver.find_element_by_name("&lpos=fp:sites:4:espnfc")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/div[2]/section[1]/div[1]/div[1]/div[1]/div[2]/button[1]")
el = driver.find_element_by_name("&lpos=fp:apps:2:espnfantasy")
el = driver.find_element_by_name("&lpos=fp:followespn:3:instagram")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[5]/section[1]/section[1]/div[1]/section[3]/div[1]/header[1]/h1[1]")
el = driver.find_element_by_name("&lpos=fp:sites:1:espndeportes")
