import time
from selenium import webdriver
driver = webdriver.Chrome("/Users/wzz/Desktop/chromedriver")
driver.get("file:///Users/wzz/Desktop/Research/scriptRepair/WebRL/website/facebook/old/index.html")
el = driver.find_element_by_link_text("Messenger")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[3]/td[2]/a[1]")
el = driver.find_element_by_link_text("Groups")
el = driver.find_element_by_link_text("Careers")
el = driver.find_element_by_id("loginbutton")
el = driver.find_element_by_link_text("Places")
el = driver.find_element_by_link_text("Create Ad")
el = driver.find_element_by_link_text("Cookies")
el = driver.find_element_by_link_text("Sign Up")
el = driver.find_element_by_link_text("Facebook Lite")
el = driver.find_element_by_link_text("Help")
el = driver.find_element_by_link_text("Locations")
el = driver.find_element_by_id("email")
el = driver.find_element_by_link_text("Forgot account?")
el = driver.find_element_by_link_text("Pages")
el = driver.find_element_by_link_text("Log In")
el = driver.find_element_by_link_text("Ad Choices")
el = driver.find_element_by_link_text("About")
el = driver.find_element_by_link_text("Developers")
el = driver.find_element_by_link_text("Games")
el = driver.find_element_by_id("pass")
el = driver.find_element_by_link_text("Create Page")
el = driver.find_element_by_link_text("Privacy")
el = driver.find_element_by_link_text("Create a Page")
el = driver.find_element_by_link_text("People")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[2]/div[1]/ul[1]/li[12]/a[1]")
