import time
from selenium import webdriver
driver = webdriver.Chrome("/Users/wzz/Desktop/chromedriver")
driver.get("file:///Users/wzz/Desktop/Research/scriptRepair/WebRL/website/facebook/old/index.html")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[3]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[3]/td[2]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[3]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[9]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/form[1]/table[1]/tbody[1]/tr[2]/td[3]/label[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[10]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[6]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[11]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[4]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[3]/td[3]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/form[1]/table[1]/tbody[1]/tr[2]/td[1]/input[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/form[1]/table[1]/tbody[1]/tr[3]/td[2]/div[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[9]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[2]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[3]/td[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[5]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[8]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[11]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/form[1]/table[1]/tbody[1]/tr[2]/td[2]/input[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[7]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[10]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[8]/a[1]")
