import time
from selenium import webdriver
driver = webdriver.Chrome("/Users/wzz/Desktop/chromedriver")
driver.get("file:///Users/wzz/Desktop/Research/scriptRepair/WebRL/website/fidelity/old/index.html")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[3]/ul[1]/li[1]/div[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/h2[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[1]/div[3]/ul[1]/li[2]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[3]/ul[1]/li[5]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[1]/div[4]/form[1]/div[1]/input[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[3]/ul[1]/li[2]/div[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[1]/div[2]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[1]/div[3]/ul[1]/li[3]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[3]/ul[1]/li[4]/div[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[1]/div[4]/form[1]/input[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/p[2]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/h2[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/h1[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[1]/div[3]/ul[1]/li[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[1]/div[3]/ul[1]/li[4]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[3]/ul[1]/li[3]/div[1]/a[1]")
