import time
from selenium import webdriver
driver = webdriver.Chrome("/Users/wzz/Desktop/chromedriver")
driver.get("file:///Users/wzz/Desktop/Research/scriptRepair/WebRL/website/fidelity/old/index.html")
el = driver.find_element_by_link_text("Accounts & Trade")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/h2[1]")
el = driver.find_element_by_link_text("OPEN AN ACCOUNT")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[3]/ul[1]/li[5]")
el = driver.find_element_by_id("Link_1426132559014")
el = driver.find_element_by_id("nav-search-mobile")
el = driver.find_element_by_link_text("Planning & Advice")
el = driver.find_element_by_id("Link_1476122135908")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[1]/div[2]/a[1]")
el = driver.find_element_by_link_text("REFER A FRIEND")
el = driver.find_element_by_link_text("Investment Products")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[1]/div[4]/form[1]/input[1]")
el = driver.find_element_by_id("Link_1482434357234")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/h2[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/h1[1]")
el = driver.find_element_by_link_text("CUSTOMER SERVICE")
el = driver.find_element_by_id("Link_1482509192388")
el = driver.find_element_by_link_text("LOG IN")
el = driver.find_element_by_link_text("News & Research")
