import time
from selenium import webdriver
driver = webdriver.Chrome("/Users/wzz/Desktop/chromedriver")
driver.get("file:///Users/wzz/Desktop/Research/scriptRepair/WebRL/website/force/old/index.html")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/div[2]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/nav[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[4]/div[1]/ul[1]/li[8]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/div[2]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[3]/h2[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/nav[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[4]/div[1]/ul[1]/li[4]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[3]/div[1]/div[1]/div[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/div[2]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[3]/div[1]/div[3]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/nav[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[4]/div[1]/ul[1]/li[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/nav[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[4]/div[1]/ul[1]/li[6]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/div[2]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[1]/h2[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/div[2]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[4]/h2[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/nav[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[4]/div[1]/ul[1]/li[3]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/div[2]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[3]/div[1]/div[6]/div[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/nav[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[4]/div[1]/ul[1]/li[7]")
el = driver.find_element_by_xpath("/html[1]/body[1]/nav[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[4]/div[1]/ul[1]/li[5]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/div[2]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[2]/h2[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/div[2]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[6]/h2[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/nav[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[4]/div[1]/ul[1]/li[2]")
