import time
from selenium import webdriver
driver = webdriver.Chrome("/Users/wzz/Desktop/chromedriver")
driver.get("file:///Users/wzz/Desktop/Research/scriptRepair/WebRL/website/google/old/index.html")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/ol[1]/li[8]/a[1]/span[2]")
el = driver.find_element_by_name("btnI")
el = driver.find_element_by_link_text("Terms")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/ol[1]/li[3]/a[1]/span[2]")
el = driver.find_element_by_name("q")
el = driver.find_element_by_link_text("Business Solutions")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/ol[1]/li[6]/a[1]/span[2]")
el = driver.find_element_by_id("gbztms1")
el = driver.find_element_by_name("btnG")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/ol[1]/li[1]/a[1]/span[2]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/ol[1]/li[4]/a[1]/span[2]")
el = driver.find_element_by_id("gbi5")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/ol[1]/li[7]/a[1]/span[2]")
el = driver.find_element_by_link_text("Advertising Programs")
el = driver.find_element_by_link_text("Privacy")
el = driver.find_element_by_link_text("Advanced search")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/ol[1]/li[2]/a[1]/span[2]")
el = driver.find_element_by_link_text("About Google")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/ol[1]/li[5]/a[1]/span[2]")
el = driver.find_element_by_id("gbi4s1")
