import time
from selenium import webdriver
driver = webdriver.Chrome("/Users/wzz/Desktop/chromedriver")
driver.get("file:///Users/wzz/Desktop/Research/scriptRepair/WebRL/website/indeed/old/index.html")
el = driver.find_element_by_id("userOptionsLabel")
el = driver.find_element_by_id("what")
el = driver.find_element_by_link_text("About")
el = driver.find_element_by_link_text("Post your resume")
el = driver.find_element_by_id("empLink")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[1]/form[1]/table[1]/tbody[1]/tr[1]/td[1]/label[1]")
el = driver.find_element_by_id("where")
el = driver.find_element_by_link_text("Browse Jobs")
el = driver.find_element_by_link_text("Upload your resume")
el = driver.find_element_by_link_text("Help Center")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[1]/form[1]/table[1]/tbody[1]/tr[1]/td[2]/label[1]")
el = driver.find_element_by_id("fj")
el = driver.find_element_by_id("salaries_product_link")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/img[1]")
