import time
from selenium import webdriver
driver = webdriver.Chrome("/Users/wzz/Desktop/chromedriver")
driver.get("file:///Users/wzz/Desktop/Research/scriptRepair/WebRL/website/instagram/old/index.html")
el = driver.find_element_by_xpath("/html[1]/body[1]/span[1]/section[1]/main[1]/article[1]/div[2]/div[3]/p[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/span[1]/section[1]/footer[1]/div[1]/nav[1]/ul[1]/li[11]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/span[1]/section[1]/main[1]/article[1]/div[2]/div[1]/div[1]/form[1]/div[5]/div[1]/div[1]/label[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/span[1]/section[1]/footer[1]/div[1]/nav[1]/ul[1]/li[5]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/span[1]/section[1]/main[1]/article[1]/div[2]/div[3]/div[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/span[1]/section[1]/footer[1]/div[1]/nav[1]/ul[1]/li[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/span[1]/section[1]/footer[1]/div[1]/nav[1]/ul[1]/li[8]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/span[1]/section[1]/main[1]/article[1]/div[2]/div[1]/h1[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/span[1]/section[1]/main[1]/article[1]/div[2]/div[1]/div[1]/form[1]/div[6]/span[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/span[1]/section[1]/footer[1]/div[1]/nav[1]/ul[1]/li[6]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/span[1]/section[1]/main[1]/article[1]/div[2]/div[3]/div[1]/a[2]")
el = driver.find_element_by_xpath("/html[1]/body[1]/span[1]/section[1]/footer[1]/div[1]/nav[1]/ul[1]/li[7]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/span[1]/section[1]/main[1]/article[1]/div[2]/div[1]/div[1]/form[1]/div[2]/div[1]/div[1]/label[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/span[1]/section[1]/main[1]/article[1]/div[2]/div[2]/p[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/span[1]/section[1]/footer[1]/div[1]/nav[1]/ul[1]/li[3]/a[1]")
