import time
from selenium import webdriver
driver = webdriver.Chrome("/Users/wzz/Desktop/chromedriver")
driver.get("https://web.archive.org/web/20190401223517if_/https://www.intuit.com/")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/section[1]/section[1]/div[1]/div[1]/section[1]/div[1]/section[2]/div[1]/section[3]/div[1]/div[1]/div[1]/ul[1]/li[4]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/section[1]/section[1]/div[1]/div[1]/section[1]/div[1]/section[1]/div[1]/ul[1]/li[2]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/section[1]/section[1]/div[1]/div[1]/section[1]/div[1]/section[2]/div[1]/section[3]/div[1]/div[1]/div[1]/ul[1]/li[2]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/section[1]/section[1]/div[1]/div[1]/section[1]/div[1]/section[2]/div[1]/section[4]/div[1]/div[1]/button[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/section[1]/section[1]/div[1]/div[1]/section[1]/div[1]/section[2]/div[1]/section[2]/div[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/section[1]/section[1]/div[1]/div[1]/section[1]/div[1]/section[1]/div[1]/ul[1]/li[3]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/section[1]/section[1]/div[1]/div[1]/section[1]/div[1]/section[1]/div[1]/div[1]/span[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/section[1]/section[1]/div[1]/div[1]/section[1]/div[1]/section[2]/div[1]/section[3]/div[1]/div[1]/div[1]/ul[1]/li[3]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/section[1]/section[1]/div[1]/div[1]/section[1]/div[1]/section[1]/div[1]/ul[1]/li[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/section[1]/section[1]/div[1]/div[1]/section[1]/div[1]/section[2]/div[1]/section[3]/div[1]/div[1]/div[1]/ul[1]/li[1]/a[1]")
el = driver.find_element_by_link_text("Sign In")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/section[1]/section[1]/div[1]/div[1]/section[1]/div[1]/section[2]/div[1]/section[2]/div[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/header[1]/section[1]/section[1]/div[1]/div[1]/section[1]/div[1]/section[2]/div[1]/section[4]/div[1]")
