import time
from selenium import webdriver
driver = webdriver.Chrome("/Users/wzz/Desktop/chromedriver")
driver.get("file:///Users/wzz/Desktop/Research/scriptRepair/WebRL/website/office/old/index.html")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/header[1]/div[1]/div[1]/nav[1]/ul[1]/li[8]/a[1]")
el = driver.find_element_by_id("Products")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[1]/div[2]/div[1]/div[1]/ul[1]/li[2]")
el = driver.find_element_by_id("support")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/header[1]/div[1]/div[1]/div[4]/div[1]/nav[1]/ul[1]/li[1]/div[1]/button[1]")
el = driver.find_element_by_id("uhfLogo")
el = driver.find_element_by_id("resources")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[1]/div[2]/div[1]/div[1]/ul[1]/li[1]")
el = driver.find_element_by_id("My account")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/header[1]/div[1]/div[1]/div[2]/a[1]/span[1]")
el = driver.find_element_by_id("c-shellmenu_33")
el = driver.find_element_by_id("hero-header")
el = driver.find_element_by_id("hero-banner-get-office-link")
el = driver.find_element_by_id("hero-banner-sign-in-to-office-365-link")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/header[1]/div[1]/div[1]/a[1]/img[1]")
