import time
from selenium import webdriver
driver = webdriver.Chrome("/Users/wzz/Desktop/chromedriver")
driver.get("file:///Users/wzz/Desktop/Research/scriptRepair/WebRL/website/reddit/old/web.archive.org/web/20170304001524/https:/www.reddit.com/index.html")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[1]/div[1]/div[3]/ul[2]/li[5]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/form[1]/div[3]/label[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[2]/ul[1]/li[2]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[2]/ul[1]/li[7]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[1]/div[1]/div[3]/ul[1]/li[2]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[1]/div[1]/div[3]/ul[2]/li[15]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[4]/div[1]/div[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[2]/ul[1]/li[4]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/form[1]/input[2]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[1]/div[1]/div[3]/ul[2]/li[2]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[1]/div[1]/div[3]/ul[2]/li[6]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[3]/ul[1]/li[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/form[1]/div[3]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[2]/ul[1]/li[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/span[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[1]/div[1]/div[3]/ul[1]/li[3]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[1]/div[1]/div[3]/ul[2]/li[9]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[5]/div[1]/div[1]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[1]/div[1]/div[3]/ul[2]/li[3]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/form[1]/input[3]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[2]/ul[1]/li[3]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[2]/ul[1]/li[6]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/form[1]/div[3]/input[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/form[1]/div[4]/button[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[2]/a[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[1]/div[1]/div[3]/ul[1]/li[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[2]/ul[1]/li[5]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[1]/form[1]/input[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[1]/div[1]/div[3]/ul[2]/li[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[1]/div[1]/div[3]/ul[2]/li[7]/a[1]")
