import time
from selenium import webdriver
driver = webdriver.Chrome("/Users/wzz/Desktop/chromedriver")
driver.get("file:///Users/wzz/Desktop/Research/scriptRepair/WebRL/website/reddit/old/web.archive.org/web/20170304001524/https:/www.reddit.com/index.html")
el = driver.find_element_by_link_text("NEWS")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/form[1]/div[3]/label[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[2]/ul[1]/li[2]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[2]/ul[1]/li[7]")
el = driver.find_element_by_link_text("ALL")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[1]/div[1]/div[3]/ul[2]/li[15]/a[1]")
el = driver.find_element_by_link_text("Submit a new link")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[2]/ul[1]/li[4]")
el = driver.find_element_by_name("user")
el = driver.find_element_by_link_text("FUNNY")
el = driver.find_element_by_link_text("WORLDNEWS")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[3]/ul[1]/li[1]")
el = driver.find_element_by_link_text("reset password")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[2]/ul[1]/li[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/span[1]")
el = driver.find_element_by_link_text("RANDOM")
el = driver.find_element_by_link_text("IAMA")
el = driver.find_element_by_link_text("Submit a new text post")
el = driver.find_element_by_link_text("TODAYILEARNED")
el = driver.find_element_by_name("passwd")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[2]/ul[1]/li[3]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[2]/ul[1]/li[6]")
el = driver.find_element_by_id("rem-login-main")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[3]/div[2]/form[1]/div[4]/button[1]")
el = driver.find_element_by_id("header-img")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[1]/div[1]/div[3]/ul[1]/li[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[2]/ul[1]/li[5]")
el = driver.find_element_by_name("q")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[1]/div[1]/div[3]/ul[2]/li[1]")
el = driver.find_element_by_link_text("PICS")
