import time
from selenium import webdriver
driver = webdriver.Chrome("/Users/wzz/Desktop/chromedriver")
driver.get("https://web.archive.org/web/20170702000250if_/https://twitter.com/")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[3]/div[1]/div[1]/div[4]/ul[1]/li[4]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[3]/div[1]/div[1]/div[4]/ul[1]/li[11]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[3]/div[1]/div[1]/div[4]/ul[1]/li[16]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[3]/div[1]/div[1]/div[2]/div[2]/form[1]/table[1]/tbody[1]/tr[1]/td[2]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[3]/div[1]/div[1]/div[4]/ul[1]/li[8]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[3]/div[1]/div[1]/div[4]/ul[1]/li[13]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[3]/div[1]/div[1]/div[4]/ul[1]/li[2]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[3]/div[1]/div[1]/div[4]/ul[1]/li[5]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[3]/div[1]/div[1]/div[4]/ul[1]/li[10]")
el = driver.find_element_by_id("signin-email")
el = driver.find_element_by_link_text("Forgot password?")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[3]/div[1]/div[1]/div[4]/ul[1]/li[6]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[3]/div[1]/div[1]/div[4]/ul[1]/li[3]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[3]/div[1]/div[1]/div[4]/ul[1]/li[12]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[3]/div[1]/div[1]/div[4]/ul[1]/li[15]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[3]/div[1]/div[1]/div[4]/ul[1]/li[9]")
el = driver.find_element_by_id("signin-password")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[3]/div[1]/div[1]/div[4]/ul[1]/li[14]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[3]/div[1]/div[1]/div[4]/ul[1]/li[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[3]/div[1]/div[1]/div[4]/ul[1]/li[7]")
