import time
from selenium import webdriver
driver = webdriver.Chrome("/Users/wzz/Desktop/chromedriver")
driver.get("file:///Users/wzz/Desktop/Research/scriptRepair/WebRL/website/yahoo/old/index.html")
el = driver.find_element_by_link_text("News")
el = driver.find_element_by_link_text("Today")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/table[1]/tbody[1]/tr[1]/td[2]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[7]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/h2[1]/span[1]")
el = driver.find_element_by_id("ysp-more-scores")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[3]/a[1]/span[1]")
el = driver.find_element_by_link_text("Finance")
el = driver.find_element_by_link_text("Yesterday")
el = driver.find_element_by_id("uh-logo")
el = driver.find_element_by_id("uh-signin")
el = driver.find_element_by_link_text("Entertainment")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/a[1]/span[1]")
el = driver.find_element_by_link_text("Tomorrow")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[7]/div[1]/div[4]/div[1]/div[6]/div[1]/div[1]/div[1]/h2[1]")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/table[1]/tbody[1]/tr[1]/td[1]")
el = driver.find_element_by_id("uh-notifications")
el = driver.find_element_by_link_text("Sports")
el = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/h1[1]")
el = driver.find_element_by_id("uh-search-button")
